### PR TITLE
Multiple CCPs in MarginClientExample

### PR DESCRIPTION
**Pull request by cjkent**
Adds files for LCH and ICE SPAN plus the ability to run one or more CCPs at the same time.

The default behaviour is unchanged (running LCH calcs).

### CODE REVIEW

**Review by akshaishah — APPROVED** [review]

**Comment by akshaishah** [comment]
@cjkent do you still want this?

**Comment by cjkent** [comment]
I think it's still worth having. The issue is that the build was already broken when I started making my changes.

Maybe the build has been fixed in the intervening 8 months and I can merge `main` and everything will work.

**Comment by cjkent** [comment]
The integration tests were broken and they still are and I have absolutely no idea why. Which is why I never followed up on this PR.

**Comment by jodastephen** [comment]
@cjkent Can you recheck this now the build passes, thx

**Pull request merged**
